owner: purrbot-site
repo: Status

sites:
  - name: Bot
    url: https://purrbot.site/shards
    icon: https://purrbot.site/assets/img/avatar.png
  - name: Website
    url: https://purrbot.site
    icon: https://purrbot.site/assets/img/avatar.png
  - name: 'Purrbot API [api.purrbot.site/*]'
    url: https://api.purrbot.site
    icon: https://purrbot.site/assets/img/avatar.png
  - name: 'Legacy API [/api/*]'
    url: https://purrbot.site/api/info
    icon: https://purrbot.site/assets/img/avatar.png

status-website:
  themeUrl: https://status.purrbot.site/discord-theme.css
  cname: status.purrbot.site
  logoUrl: https://purrbot.site/assets/img/avatar.png
  favicon: https://purrbot.site/assets/img/avatar.png
  name: PurrBot Status
  introTitle: "Status page of all services offered under purrbot.site, including the Bot."
  introMessage: |-
    On this website can you see the current status of the Discord Bot &lowast;Purr&lowast;, [the website](https://purrbot.site) and the different [ImageAPI endpoints](https://docs.purrbot.site/api).
    The entire page is [open source](https://github.com/purrbot-site/Status) and powered by [Upptime](https://upptime.js.org)!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://purrbot.site
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://purrbot.site/discord
  metaTags:
    - name: "theme-color"
      content: "#3F51B5"
    - name: "description"
      content: "Status page for various services of purrbot.site including the bot."
    - name: "twitter:card"
      content: "summary"
    - name: "twitter:title"
      content: "PurrBot Status"
    - name: "twitter:description"
      content: "Status page for various services of purrbot.site including the bot."
    - name: "twitter:image"
      content: "https://purrbot.site/assets/img/avatar.png"
    - name: "og:site_name"
      content: "PurrBot Status"
    - name: "og:title"
      content: "PurrBot Status"
    - name: "og:url"
      content: "https://status.purrbot.site"
    - name: "og:description"
      content: "Status page for various services of purrbot.site including the bot."
    - name: "og:image"
      content: "https://purrbot.site/assets/img/avatar.png"

assignees:
  - Andre601
