owner: purrbot-site
repo: Status

sites:
  - name: Bot
    url: https://purrbot.site/shards
    icon: https://purrbot.site/assets/img/avatar.png
  - name: Website
    url: https://purrbot.site
    icon: https://purrbot.site/assets/img/avatar.png
  - name: 'Images API [/api/img/*]'
    url: https://purrbot.site/api/img/sfw/background/img
    icon: https://purrbot.site/assets/img/avatar.png
  - name: 'Quote Image API [/api/quote]'
    url: https://purrbot.site/api/quote
    method: POST
    headers:
      - "Content-Type: application/json"
    body: "{}"
    icon: https://purrbot.site/assets/img/avatar.png
  - name: 'Status Image API [/api/status]'
    url: https://purrbot.site/api/status
    method: POST
    headers:
      - "Content-Type: application/json"
    body: "{}"
    icon: https://purrbot.site/assets/img/avatar.png

status-website:
  theme: dark
  cname: status.purrbot.site
  logoUrl: https://purrbot.site/assets/img/avatar.png
  favicon: https://purrbot.site/assets/img/avatar.png
  name: Uptime PurrBot
  introTitle: "Status page of all services offered under purrbot.site, including the Bot."
  introMessage: |-
    On this website can you see the current status of the Discord Bot *Purr*, [the website](https://purrbot.site) and the different [ImageAPI endpoints](https://docs.purrbot.site/api).
    The entire page is [open source](https://github.com/purrbot-site/Status) and powered by [Upptime](https://upptime.js.org)!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://purrbot.site
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://purrbot.site/discord

assignees:
  - Andre601
